"""add warehouse tables

Revision ID: d3c6a5620b30
Revises: ed99ea2e8cfb
Create Date: 2025-12-26 10:10:27.877808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c6a5620b30'
down_revision: Union[str, Sequence[str], None] = 'ed99ea2e8cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_created_at'), 'games', ['created_at'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_nba_game_id'), 'games', ['nba_game_id'], unique=True)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_game_id', sa.String(), nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=False),
    sa.Column('nba_team_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_game_id', 'nba_player_id', name='uq_player_game')
    )
    op.create_index(op.f('ix_player_game_stats_created_at'), 'player_game_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_player_game_stats_id'), 'player_game_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_nba_game_id'), 'player_game_stats', ['nba_game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_nba_player_id'), 'player_game_stats', ['nba_player_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_nba_team_id'), 'player_game_stats', ['nba_team_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('nba_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_created_at'), 'players', ['created_at'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_nba_player_id'), 'players', ['nba_player_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nba_team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_nba_team_id'), 'teams', ['nba_team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic###
    op.drop_index(op.f('ix_teams_nba_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_nba_player_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_created_at'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_player_game_stats_nba_team_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_nba_player_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_nba_game_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_created_at'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_nba_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_created_at'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
